<?php
$lang['int_foo_01'] = 'ForexMart';
$lang['int_foo_02'] = 'ForexMart';
$lang['int_foo_03'] = 'ForexMart';

$lang['rw'] = 'Cảnh báo Rủi ro&#58;';
$lang['rw1'] = 'Ngoại hối có tính chất đầu cơ cao và phức tạp, và có thể không phù hợp với tất cả các nhà đầu tư. Giao dịch ngoại hối có thể dẫn đến lãi hoặc lỗ đáng kể. Vì vậy, không nên đầu tư số tiền mà bạn không thể để mất. Trước khi sử dụng các dịch vụ được cung cấp bởi';
$lang['rw2'] = 'ForexMart';
$lang['rw3'] = '&#44; vui lòng thừa nhận và hiểu';
$lang['rw4'] = 'các rủi ro';
$lang['rw5'] = ' so với giao dịch ngoại hối. Tìm kiếm lời khuyên tài chính, nếu cần thiết.';
$lang['pn1-1'] ='ForexMart';
$lang['pn1-2'] ='là tên giao dịch của';
$lang['pn1-3'] ='&#44; một Công ty Đầu tư Cyprus do Sở Giao dịch Chứng khoán Cyprus (CySEC) quản lý với giấy phép số 266/15.';
$lang['pn2-1'] ='ForexMart';
// $lang['pn2-2'] ='được ShowFx World vinh danh là Nhà môi giới tốt nhất ở Châu Âu 2015 và Nhà môi giới có triển vọng nhất ở Châu Á năm 2015.';
$lang['pn2-2'] ='được ShowFx World vinh danh như ';
$lang['pn2-2-2'] ='Nhà môi giới tốt nhất ở Châu Âu 2015 và Nhà môi giới có triển vọng nhất ở Châu Á 2015.';
$lang['pn2-3'] ='không&#39; cung cấp dịch vụ của mình cho cư dân của một số khu vực pháp lý nhất định như Hoa Kỳ, Bắc Triều Tiên, Sudan và Syria.';
$lang['pn2-4'] ='- Đối tác giao dịch ngoại hối chính thức của U.D. Las Palmas.';

$lang['pn2-5'] =' được Tạp chí Tài chính Quốc tế (IFM) trao tặng là "Nhà môi giới mới tốt nhất Châu Âu 2016" ';
$lang['pn2-6'] =' là tên giao dịch của';
$lang['pn2-7'] ='Công ty hoạt động dưới sự quản lý của Ủy ban Chứng khoán và Sàn giao dịch Cyprus (CySEC) (số giấy phép <a href="http://www.cysec.gov.cy/en-GB/entities/investment-firms/cypriot/71294/">266/15</a>) và được đăng ký theo các cơ quan quản lý của EU như sau: Autorité de Contrôle Prudentiel et de Résolution của Pháp (ACPR) (Số đăng ký 75426), Cơ quan Giám sát Tài chính Liên bang Đức (BaFin) (số đăng ký 146395), và Cơ quan Quản lý Tài chính Anh (FCA) (số đăng ký 728735). ForexMart là thành viên được chứng nhận của Quỹ Bồi thường Nhà đầu tư (ICF) và tuân thủ MiFID theo Dịch vụ Đầu tư và Luật Quản lý của Thị trường năm 2007 (luật số 144 (I) 2007). Forexmart được cấp phép cung cấp các dịch vụ đầu tư khác nhau như Tiếp nhận và chuyển lệnh liên quan đến một hoặc nhiều công cụ tài chính, Thực hiện lệnh đại diện cho khách hàng, Giao dịch trên tài khoản của chính mình, Quản lý danh mục đầu tư, Lưu giữ an toàn và quản lý các công cụ tài chính cho tài khoản của khách hàng , bao gồm quyền giám hộ và các dịch vụ liên quan như quản lý tiền mặt / tài sản thế chấp, Cấp tín dụng hoặc khoản vay cho nhà đầu tư để cho phép nhà đầu tư thực hiện giao dịch bằng một hoặc nhiều công cụ tài chính, trong đó công ty cấp tín dụng hoặc khoản vay có liên quan đến giao dịch, các dịch vụ ngoại hối trong đó các dịch vụ này được kết nối với việc cung cấp các dịch vụ đầu tư và Nghiên cứu đầu tư và phân tích tài chính hoặc các hình thức khuyến nghị chung khác liên quan đến các giao dịch trong các công cụ tài chính. Tất cả các dịch vụ này được cung cấp liên quan đến các công cụ tài chính (chứng khoán có thể chuyển nhượng, quyền chọn, hợp đồng tương lai, SWAPS, thỏa thuận tỷ giá kỳ hạn, CFD và các công cụ phái sinh khác).';
$lang['pn2-8'] ='Công ty hoạt động dưới sự quản lý của Ủy ban Chứng khoán và Giao dịch Cyprus (CySEC) (số giấy phép';
$lang['pn2-9'] =') và được đăng ký theo các cơ quan quản lý của Liên minh Châu Âu như sau: Autorité de Contrôle Prudentiel et de Résolution của Pháp (ACPR) (Số đăng ký 75426), Cơ quan Giám sát Tài chính Liên bang Đức (BaFin) (đăng ký số 146395), và Cơ quan Quản lý Tài chính Anh (FCA) (số đăng ký 728735). ForexMart là thành viên được chứng nhận của Quỹ Bồi thường Nhà đầu tư (ICF) và tuân thủ MiFID theo Dịch vụ Đầu tư và Luật Quản lý của Thị trường năm 2007 (luật số 144 (I) 2007). Forexmart được cấp phép cung cấp các dịch vụ đầu tư khác nhau như Tiếp nhận và chuyển lệnh liên quan đến một hoặc nhiều công cụ tài chính, Thực hiện lệnh đại diện cho khách hàng, Giao dịch trên tài khoản của chính mình, Quản lý danh mục đầu tư, Lưu giữ an toàn và quản lý các công cụ tài chính cho tài khoản của khách hàng , bao gồm quyền giám hộ và các dịch vụ liên quan như quản lý tiền mặt / tài sản thế chấp, Cấp tín dụng hoặc khoản vay cho nhà đầu tư để cho phép nhà đầu tư thực hiện giao dịch bằng một hoặc nhiều công cụ tài chính, trong đó công ty cấp tín dụng hoặc khoản vay có liên quan đến giao dịch, các dịch vụ ngoại hối trong đó các dịch vụ này được kết nối với việc cung cấp các dịch vụ đầu tư và Nghiên cứu đầu tư và phân tích tài chính hoặc các hình thức khuyến nghị chung khác liên quan đến các giao dịch trong các công cụ tài chính. Tất cả các dịch vụ này được cung cấp liên quan đến các công cụ tài chính (chứng khoán có thể chuyển nhượng, quyền chọn, hợp đồng tương lai, SWAPS, thỏa thuận tỷ giá kỳ hạn, CFD và các công cụ phái sinh khác).';

//if(IPLoc::Office()){
//    $lang['pn2-7'] ='Công ty hoạt động dưới sự quản lý của Ủy ban Chứng khoán và Giao dịch Cyprus (CySEC) (số giấy phép <a href="'.FXPP::www_url('License').'">266/15</a>) và đã được đăng ký dưới các cơ quan quản lý của EU như sau: Autorité de Contrôle Prudentiel và de Résolution của Pháp (ACPR) (Số đăng ký 75426), Cơ quan Giám sát Tài chính Liên bang Đức (BaFin) (số đăng ký 146395) và Cơ quan Quản lý Tài chính Anh (FCA) (đăng ký số 728735). ForexMart là thành viên được chứng nhận của Quỹ Bồi thường Nhà đầu tư (ICF) và tuân thủ MiFID theo Dịch vụ Đầu tư và Luật Quy định của Thị trường năm 2007 (luật số 144 (I) 2007). Forexmart được cấp phép cung cấp các dịch vụ đầu tư khác nhau như Tiếp nhận và chuyển lệnh liên quan đến một hoặc nhiều công cụ tài chính, Thực hiện lệnh đại diện cho khách hàng, Giao dịch trên tài khoản của chính mình, Quản lý danh mục đầu tư, Lưu giữ an toàn và quản lý các công cụ tài chính cho tài khoản của khách hàng , bao gồm giám sát và các dịch vụ liên quan như quản lý tiền mặt / tài sản thế chấp, Cấp tín dụng hoặc khoản vay cho nhà đầu tư để cho phép nhà đầu tư thực hiện giao dịch bằng một hoặc nhiều công cụ tài chính, trong đó công ty cấp tín dụng hoặc khoản vay có liên quan đến giao dịch, dịch vụ ngoại hối trong đó các dịch vụ này được kết nối với việc cung cấp các dịch vụ đầu tư và Nghiên cứu đầu tư và phân tích tài chính hoặc các hình thức khuyến nghị chung khác liên quan đến các giao dịch trong các công cụ tài chính. Tất cả các dịch vụ này được cung cấp liên quan đến các công cụ tài chính (chứng khoán có thể chuyển nhượng, quyền chọn, hợp đồng tương lai, SWAPS, thỏa thuận tỷ giá kỳ hạn, CFD và các công cụ phái sinh khác).';
//}