<style>
    #error-container p{
        color: red;
    }
</style>

<div class="reg-form-holder signin-form-holder">
    <div class="sign-in-container-holder client-form-holder">
        <div class="signin-box-container">
            <div class="signin-box-holder-content">

                <div class="col-lg-12 col-md-12 col-centered">
                    <div class="verification-page">
                        <h1 class="info-text"> 2-Step Verification </h1>
                        <div class="mob-img-holder">
                            <img src="<?= $this->template->Images()?>mobile-ver.png" class="img-responsive">
                        </div>
                        <div class="step2-text">
                            <h4>Enter the verification code generated by your mobile application</h4>
                        </div>

                        <div class="step2-input-holder" id="tfasigninboxpanel">
                                <?php if($this->session->flashdata('validation_errors')): ?>
                                    <div id="error-container" class="error">
                                        <?= $this->session->flashdata('validation_errors'); ?>
                                    </div>
                                <?php endif; ?>
                                <form id="tfa-login-form" onsubmit="return validateForm(this)" method="POST" action="<?=FXPP::my_url('two-step-authentication/verify')?>" autocomplete="off">
                                    <input type="text" name="verification_code" id="verification_code_data" class="txt-entercode onlynumberfield" placeholder="Enter code">
                                    <button type="submit" class="btn btn-primary round-0 btn-ver">Verify</button>
                                </form>
                            </div>

                    </div>
                </div>
            </div>
        </div>
    </div>
</div>




<script>
   
   
   
function checkCodeLength(data)
{
    data=data.trim();
    if(data.length==6)
    {
        return true;
    }else{
        return false;
    }
}

$('.onlynumberfield').on('keypress', function (event) {
      $("#tfasigninboxpanel").find("#error-container").remove();
    
    var regex = new RegExp("^[0-9]+$");
    var key = String.fromCharCode(!event.charCode ? event.which : event.charCode);
    if (!regex.test(key)) {
       event.preventDefault();
       return false;
    }
});

     
function validateForm(form_obj) {
    

  $("#tfasigninboxpanel").find("#error-container").remove();
  var error_mgs='<div id="error-container" class="error"><p><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">Invalid code</font></font></p> </div>';
   
    
   var code=document.getElementById("verification_code_data").value ;
    if(checkCodeLength(code))
    {
       //  setTimeout(function() {
            // console.log("request done");
            form_obj.submit();
      //  }, 5000); // 3 seconds[3000]
        
        return false;
    }
    else{
        $("#tfasigninboxpanel").prepend(error_mgs);
        return false;
    }
}    
    
    
$(document).on("keyup","#verification_code_data",function(e){
    
     if (e.key === 'Enter' || e.keyCode === 13) {
        $("#tfa-login-form").submit();
    }
});    
    
</script>    
 

                                