<style type="text/css">
    .txtcode{
        color: #5a5a5a !important;
    }
    
 @media (max-width: 767px){
.modal-dialog {
    width: 600px !important;
    margin: 30px auto !important;
}    
}

@media (max-width: 500px){
.modal-dialog {
    width: 350px !important;
    margin: 10% !important;
}    
}
@media (max-width: 430px){
.modal-dialog {
    width: 280px !important;
    margin: 15% !important;
}    
}
@media (max-width: 400px){
.modal-dialog {
    width: 250px !important;
    margin: 12% !important;
}    
}

</style>
<div class="modal fade" id="step1" tabindex="-1" data-backdrop="static" role="dialog" aria-labelledby="">
    <div class="modal-dialog round-0 step2-dialog">
        <div class="modal-content round-0">
            <div class="modal-header round-0">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                <h4 class="modal-title modal-show-title">
                    2-Step Verification
                </h4>
            </div>
            <div class="modal-body modal-show-body">
                <div class="row">
                    <div class="col-md-12">
                        <div class="mob-img-holder">
                            <img src="<?= $this->template->Images()?>mobile-ver.png" class="img-responsive">
                        </div>
                    </div>
                    <div class="col-md-12 step2-text">
                        <h4>Enter the verification code generated by your mobile device application</h4>
                    </div>
                    <div class="col-md-12">
                        <div class="step2-input-holder">
                            <form  id="tfa-setup-form" method="POST" autocomplete="off">
                                <div id="error-container" class="error" style="display: none;"></div>
                                <input  onkeyup="this.value=this.value.replace(/[^\d]/,'')"  type="text" id="tfa_setup_code" name="tfa_setup_code" class="txt-entercode" placeholder="Enter code">
                                <button type="submit" class="btn btn-primary round-0 btn-ver">Verify</button>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>




 