<?php
$lang['tfa_0'] = 'Your account is protected by two-step verification';
$lang['tfa_off'] = 'Turn off two-step verification';
$lang['tfa_on'] = 'Turn on two-step verification';
$lang['tfa_h4'] = 'Set up Authenticator';
$lang['tfa_1'] = 'Install the Google Authenticator app for your mobile phone or tablet.';
$lang['tfa_1_1'] = '1. Visit the App Store (for iOS operating system on your phone/tablet) or Play Market (for Android system).';
$lang['tfa_1_2'] = '2. Find the Google Authenticator app.';
$lang['tfa_1_3'] = '3. Download it for free and install on your phone/tablet.';
$lang['tfa_2'] = 'Then open and configure Google Authenticator.';
$lang['tfa_2_1'] = '1. In Google Authenticator tap "+" and then "Scan Barcode".';
$lang['tfa_2_2'] = "2. Use your device's camera to scan this barcode.";

$lang['tfa_2_3'] = "3. Once you have scanned the barcode, enter the 6-digits verification code generated by the Authenticator app.";


$lang['tfa_2_manul_title'] = "CAN'T SCAN IT?";
$lang['tfa_2_manul_title_2'] = "SHOW QR-CODE";
$lang['tfa_2_manual_1'] = "1. Copy the Account number and Secret Key below";
$lang['tfa_2_manual_2'] = "2. Setup manually in the Google Authenticator on your mobile device.";
$lang['tfa_2_manual_3'] = "3. Make sure that <b>Time based</b> is turned on."; 


$lang['tfa_2_manual_4'] ="Account Number ";
$lang['tfa_2_manual_5'] ="Secret Key ";


$lang['tfa_2_manual_p'] ="Once you have scanned the barcode, enter the 6-digits verification code generated by the Authenticator app.";//' The codes reset on a countdown. Tap the code to copy that and enter the 6-digits verification code generated by the Authenticator app.';



$lang['tfa_p'] = 'Once you have scanned the barcode, enter the 6-digits verification code generated by the Authenticator app.';
$lang['tfa_cancel'] = 'Cancel';
$lang['tfa_vns'] = 'Verify and Save';
$lang['tfa_code'] = 'Code';
$lang['tfa_error_code']='Invalid code';